version: '3.8'

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: contact-manager-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - contact-manager-network

  webserver:
    image: nginx:alpine
    container_name: contact-manager-webserver
    restart: unless-stopped
    ports:
      - "8085:80"    # Puerto alternativo
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - contact-manager-network

  db:
    image: mysql:8.0
    container_name: contact-manager-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"  # Puerto alternativo para MySQL
    networks:
      - contact-manager-network

volumes:
  dbdata:

networks:
  contact-manager-network:
    driver: bridge